Repository hazelcast/hazelcast-jet, pull requests merged in 2018-07, with the labels that each got.

#931 Add jdbc connector
  hazelcast-jet-core/pom.xml
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SinkProcessors.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/processor/SourceProcessors.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadJdbcP.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteJdbcP.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/ToResultSetFunction.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/ReadJdbcPTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteJdbcPTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/PipelineTestSupport.java
Labels: core, enhancement

#952 Add jms api as a dependency for javadoc plugin
  hazelcast-jet-all/pom.xml
Labels: defect, javadoc

#950 Add JetClientConfig which uses the correct group name and password
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/Jet.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetClientConfig.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetConfig.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/JetInstanceTest.java
Labels: enhancement

#960 Improve javadoc of AggregateOperation.andThen
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperation.java
Labels: enhancement, javadoc

#961 Make it possible to use DistributedCollector as a plain Collector
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/stream/DistributedCollector.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/aggregate/AggregateOperationsTest.java
Labels: core, enhancement, pipeline-api

#962 Avro dependency should not be provided scope
  hazelcast-jet-avro/pom.xml
Labels: avro, defect

#964 Add Tuple4 and Tuple5
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/Tuple4.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/Tuple5.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/datamodel/Tuple4Test.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/datamodel/Tuple5Test.java
Labels: enhancement

#965 Add Tuple4,5 serializer hooks
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/DataModelSerializerHooks.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization/SerializerHookConstants.java
  hazelcast-jet-core/src/main/resources/META-INF/services/com.hazelcast.SerializerHook
Labels: defect

#967 bufferFn should be created once per processor
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java
Labels: defect

#969 Avro generic parameters cleanup, and add convenience for builder
  hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroProcessors.java
  hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroSourceBuilder.java
  hazelcast-jet-avro/src/main/java/com/hazelcast/jet/avro/AvroSources.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperation1.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadFilesP.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/FileSinkBuilder.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/FileSourceBuilder.java
Labels: avro, enhancement

#972 Add spring and avro modules to distribution
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java
  hazelcast-jet-distribution/pom.xml
  hazelcast-jet-distribution/src/assembly/zip.xml
Labels: avro, defect, spring

#930 Add unit to Jet probes [MERGE AFTER 3.10.3]
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorTasklet.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java
  pom.xml
Labels: core, enhancement

#974 Add getter for HazelcastClient on JetClientInstanceImpl
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetClientInstanceImpl.java
Labels: enhancement

#971 Cleanup of distribution module
  hazelcast-jet-all/pom.xml
  hazelcast-jet-client-protocol/pom.xml
  hazelcast-jet-distribution/pom.xml
  hazelcast-jet-distribution/src/assembly/zip.xml
  hazelcast-jet-distribution/src/main/resources/bin/common.sh
  hazelcast-jet-distribution/src/main/resources/bin/jet-start.bat
  hazelcast-jet-distribution/src/main/resources/bin/jet-submit.bat
  hazelcast-jet-distribution/src/main/resources/changelog.txt
  hazelcast-jet-distribution/src/main/resources/release_notes.txt
  hazelcast-jet-hadoop/pom.xml
  hazelcast-jet-spring/pom.xml
  pom.xml
Labels: core, enhancement

#976 Do not tag snapshot restore vertices with source=yes
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/DAG.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/OutboxImpl.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/EdgeDef.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/VertexDef.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/DotTest.java
Labels: core, enhancement
