Repository hazelcast/hazelcast-jet, pull requests merged in 2019-04, with the labels that each got.

#1327 Hash Join support for non-distinct keys #1326
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/HashJoinCollectP.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/HashJoinP.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/package-info.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/HashJoinPTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/BatchStageTest.java
Labels: enhancement

#1347 Changelog and release notes for 3.0
  hazelcast-jet-distribution/src/main/resources/changelog.txt
  hazelcast-jet-distribution/src/main/resources/release_notes.txt
Labels: javadoc

#1356 Fix for string representation of Tuple4 and Tuple5
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/Tuple4.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/Tuple5.java
Labels: defect, pipeline-api

#1346 Logger name & catching up in mapJournal
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ConvenientSourceP.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sources.java
Labels: enhancement

#1368 Add workaround for including javadoc from core module into distribution
  hazelcast-jet-distribution/pom.xml
Labels: defect, javadoc

#1367 Add workaround for including javadoc from core module into distribution
  hazelcast-jet-distribution/pom.xml
Labels: defect, javadoc

#1350 Fixed nightly profile
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/benchmark/BackpressureTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/benchmark/WordCountTest.java
  pom.xml
Labels: build

#1354 Fully garbage free iteration in HashJoinP
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Outbox.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/DataModelSerializerHooks.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/datamodel/ItemsByTag.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/HashJoinP.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/processor/HashJoinPTest.java
Labels: core, enhancement

#1372 Update Readme
  README.md
Labels: javadoc

#1325 Subsequent transform fusing
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/ComputeStageImplBase.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/Planner.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/AbstractTransform.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/FilterTransform.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/FlatMapTransform.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/MapTransform.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamStageTest.java
Labels: enhancement, pipeline-api

#1386 Set Kafka version to 2.2.0 (Scala 2.12)
  hazelcast-jet-kafka/pom.xml
Labels: enhancement, kafka

#1376 Improve ignored duplicate job submission logs
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJetInstance.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/AbstractJobProxy.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobTest.java
Labels: core, enhancement

#1369 Add `filtering` and `flatMapping` AggrOp wrappers
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/aggregate/AggregateOperations.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/aggregate/AggregateOperationsTest.java
Labels: enhancement, pipeline-api

#1387 Small javadoc improvements
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/SourceBuilder.java
Labels: enhancement
