Repository hazelcast/hazelcast-jet, pull requests merged in 2020-10, with the labels that each got.

#2566 Define package of the class before defining the class in JetClassLoader
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/JetClassLoader.java
Labels: defect

#2582 Use custom CL for Comparator serialization
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Edge.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/EdgeDef.java
Labels: defect

#2581 Improve safety of working with job suspension cause programmatically
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/Job.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/JobSuspensionCause.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/ClientJobProxy.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionRecord.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobProxy.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobSuspensionCauseImpl.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/codec/JetGetJobSuspensionCauseCodec.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetGetJobSuspensionCauseMessageTask.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/JetInitDataSerializerHook.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobSuspensionCauseOperation.java
  hazelcast-jet-core/src/main/resources/client-protocol-definition/Jet.yaml
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SuspendExecutionOnFailureTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/init/JetInitDataSerializerHookTest.java
Labels: core, pipeline-api

#2587 Increase default reconnect interval, improve docs
  extensions/cdc-mysql/src/main/java/com/hazelcast/jet/cdc/mysql/MySqlCdcSources.java
  extensions/cdc-postgres/src/main/java/com/hazelcast/jet/cdc/postgres/PostgresCdcSources.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/retry/RetryStrategies.java
Labels: cdc

#2590 Improve container cleanup, when done explicitly
  extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractCdcIntegrationTest.java
  extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java
  extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java
Labels: cdc, test-failure

#2586 Retry initialization of PythonService context
  extensions/python/src/main/java/com/hazelcast/jet/python/PythonService.java
  extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java
  extensions/python/src/test/java/com/hazelcast/jet/python/PythonInitCleanupTest.java
Labels: python, test-failure

#2588 Increase default reconnect interval, improve docs
  extensions/cdc-mysql/src/main/java/com/hazelcast/jet/cdc/mysql/MySqlCdcSources.java
  extensions/cdc-postgres/src/main/java/com/hazelcast/jet/cdc/postgres/PostgresCdcSources.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/retry/RetryStrategies.java
Labels: cdc

#2593 Forward Port: Use custom CL for Comparator serialization (#2582)
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Edge.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/EdgeDef.java
Labels: backport

#2592 Retry initialization of PythonService context
  extensions/python/src/main/java/com/hazelcast/jet/python/PythonService.java
  extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java
  extensions/python/src/test/java/com/hazelcast/jet/python/PythonInitCleanupTest.java
Labels: backport, python, test-failure

#2589 Publish CDC - Elastic blog post
  site/website/blog/.2020-10-06-enabling-full-text-search.md.swp
  site/website/blog/2020-05-25-grcp.md
  site/website/blog/2020-10-06-enabling-full-text-search.md
  site/website/blog/assets/2020-10-06-architecture.png
  site/website/blog/assets/2020-10-06-global-join-step.png
  site/website/blog/assets/2020-10-06-search-george.png
  site/website/blog/assets/2020-10-06-search-rabbies.png
  site/website/blog/assets/2020-10-06-spring-petclinic-list.png
  site/website/blog/assets/2020-10-06-two-join-step.png
  site/website/pages/en/demos.js
Labels: cdc, docs-no-build, elastic

#2597 Name containers used in tests
  extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractCdcIntegrationTest.java
  extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/DebeziumCdcIntegrationTest.java
  extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/AbstractMySqlCdcIntegrationTest.java
  extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java
  extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/AbstractPostgresCdcIntegrationTest.java
  extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java
Labels: cdc

#2576 Upgrade Mockito version
  pom.xml
Labels: dependencies

#2604 Fix JDBC driver initialization deadlock
  extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSource.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadJdbcP.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteJdbcP.java
Labels: defect

#2605 Fix JDBC driver initialization deadlock [forward port of #2604]
  extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSource.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterSnapshotContext.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadJdbcP.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteJdbcP.java
Labels: defect

#2577 4.3 Release Notes and Changelog
  NOTICE
  hazelcast-jet-distribution/src/root/changelog.txt
  hazelcast-jet-distribution/src/root/release_notes.txt
Labels: docs, docs-no-build

#2578 4.3 Release Notes and Changelog (master branch)
  NOTICE
  hazelcast-jet-distribution/src/root/changelog.txt
  hazelcast-jet-distribution/src/root/release_notes.txt
Labels: docs, docs-no-build

#2580 Hazelcast Jet 4.3 Relase Blogpost
  site/website/blog/2020-10-23-jet-43-is-released.md
Labels: docs, docs-no-build

#2617 Fix broken 4.3 RN link from download page
  site/website/all-versions.json
Labels: docs, docs-no-build

#2616 Reactivate TestContainers resource reaper in CDC network tests
  extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java
  extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java
Labels: cdc, test-failure

#2579 Add Lite Member Documentation
  site/docs/operations/cluster-sizing.md
Labels: docs, docs-no-build

#2619 Migrate CDC test container related fixes from `master`
  extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractCdcIntegrationTest.java
  extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/DebeziumCdcIntegrationTest.java
  extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/AbstractMySqlCdcIntegrationTest.java
  extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java
  extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/AbstractPostgresCdcIntegrationTest.java
  extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/PostgresCdcNetworkIntegrationTest.java
Labels: cdc, test-failure

#2606 Update javadoc for Sinks.files
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteJdbcP.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/TransactionPoolSnapshotUtility.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/pipeline/Sinks.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/SnapshotContextSimpleTest.java
Labels: enhancement, javadoc, test-coverage

#2626 Code cleanup
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/MemberReconnectionStressTest.java
Labels: enhancement, javadoc

#2629 Fix WriteFileP.isCooperative (backport of #2628)
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteFileP.java
Labels: backport, defect

#2628 Fix WriteFileP.isCooperative
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/WriteFileP.java
Labels: defect

#2630 Fix getJobStatus race
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java
Labels: core, test-failure

#2627 Ignore MySql CDC tests with JDK 15
  extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/DebeziumCdcIntegrationTest.java
  extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/AbstractMySqlCdcIntegrationTest.java
  extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java
Labels: test-coverage

#2591 Improve PythonService init/cleanup
  extensions/python/src/main/java/com/hazelcast/jet/python/PythonService.java
  extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java
  extensions/python/src/test/java/com/hazelcast/jet/python/PythonInitCleanupTest.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/test/TestProcessorSupplierContext.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/Contexts.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java
  pom.xml
Labels: defect, python

#2633 Document PR trigger phrases in README
  README.md
Labels: docs-no-build
