Repository hazelcast/hazelcast-jet, pull requests merged in 2020-07, with the labels that each got.

#2385 Fix broken links in blog post
  site/website/blog/2020-06-09-jdk-gc-benchmarks-part1.md
  site/website/blog/2020-06-09-jdk-gc-benchmarks-part2.md
Labels: defect, docs, docs-no-build

#2387 [005] - Add CDC Join tutorial and fix other minor issues
  site/docs/api/sources-sinks.md
  site/docs/operations/cdc.md
  site/docs/tutorials/cdc-join.md
  site/docs/tutorials/cdc-postgres.md
  site/docs/tutorials/cdc.md
  site/website/sidebars.json
Labels: cdc, docs-no-build

#2388 [005] - Add CDC Join tutorial and fix other minor issues, prod branch migration
  site/docs/api/sources-sinks.md
  site/docs/operations/cdc.md
  site/docs/tutorials/cdc-join.md
  site/docs/tutorials/cdc-postgres.md
  site/docs/tutorials/cdc.md
  site/website/sidebars.json
Labels: cdc, docs-no-build

#2389 Handle missed exception type in observer listener
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/observer/ObservableImpl.java
Labels: core

#2396 Fix test failures on Windows
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/ResourceConfigTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/config/YamlJetConfigResolutionTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/StreamFilesPTest.java
Labels: test-failure

#2381 New front page for website
  site/website/pages/en/index.js
  site/website/siteConfig.js
  site/website/static/css/custom.css
  site/website/static/img/construction-and-tools.svg
  site/website/static/img/database.svg
  site/website/static/img/electricity.svg
  site/website/static/img/hazelcast-logo-bug.svg
  site/website/static/img/hazelcast-logo-horz.svg
  site/website/static/img/layers.svg
  site/website/static/img/layers2.svg
  site/website/static/img/lightning.svg
  site/website/static/img/logos/adobe.svg
  site/website/static/img/logos/anz.svg
  site/website/static/img/logos/betgenius.svg
  site/website/static/img/logos/bnp-paribas.svg
  site/website/static/img/logos/bnp.png
  site/website/static/img/logos/cgi.svg
  site/website/static/img/logos/codedose.png
  site/website/static/img/logos/finantix.png
  site/website/static/img/logos/flowtraders.png
  site/website/static/img/logos/plex.svg
  site/website/static/img/logos/sigmastream.png
  site/website/static/img/process.svg
  site/website/static/img/share.svg
  site/website/static/img/thunder.svg
  site/website/static/img/timer.svg
  site/website/static/img/undraw_finish_line_blue.svg
  site/website/static/img/undraw_finish_line_orange.svg
  site/website/static/img/undraw_relaxation_blue.svg
  site/website/static/img/undraw_relaxation_orange.svg
  site/website/static/img/undraw_superhero_blue.svg
  site/website/static/img/undraw_superhero_orange.svg
  site/website/static/img/undraw_working_out_blue.svg
  site/website/static/img/undraw_working_out_orange.svg
Labels: docs-no-build

#2402 Fixes to javadoc generation
  hazelcast-jet-all/pom.xml
  hazelcast-jet-distribution/pom.xml
Labels: build, defect, javadoc

#2403 Avoid shading already shaded jar
  hazelcast-jet-all/pom.xml
Labels: build

#2376 Add 4.2 release blog post
  site/website/blog/2020-07-14-jet-42-is-released.md
Labels: docs-no-build

#2404 Adapt wording in benchmark blog post to Jet 4.2 having been released
  site/website/blog/2020-06-09-jdk-gc-benchmarks-part1.md
  site/website/blog/2020-06-23-jdk-gc-benchmarks-rematch.md
Labels: docs, docs-no-build, enhancement

#2264 Add A CDC use-case for an evergreen cache blog post
  site/website/blog/2020-07-16-designing-evergreen-cache-cdc.md
  site/website/blog/assets/2020-07-16-architecture-with-cdc.svg
  site/website/blog/assets/2020-07-16-starting-architecture.svg
  site/website/blog/assets/2020-07-16-updating-database-bypassing-cache.svg
Labels: docs-no-build

#2365 Add Contrib. Modules to the Download Page
  site/website/modules.json
  site/website/pages/en/download.js
Labels: docs, docs-no-build

#2407 Add nightly tests to test-coverage profile
  extensions/elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/elastic/LocalClusterElasticSourcesTest.java
  pom.xml
Labels: build, test-coverage

#2401 [005] Add CDC example
  examples/README.md
  examples/cdc/pom.xml
  examples/cdc/src/main/java/com/hazelcast/jet/examples/cdc/Cache.java
  examples/cdc/src/main/java/com/hazelcast/jet/examples/cdc/Customer.java
  examples/pom.xml
Labels: cdc

#2406 [005] Upgrade to Debezium 1.2.1.Final
  extensions/cdc-debezium/pom.xml
  extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSource.java
  extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/DebeziumCdcIntegrationTest.java
  extensions/cdc-mysql/pom.xml
  extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcWhiteBlackListIntegrationTest.java
  extensions/cdc-postgres/pom.xml
  extensions/cdc-postgres/src/main/java/com/hazelcast/jet/cdc/postgres/PostgresCdcSources.java
  hazelcast-jet-distribution/src/root/NOTICE
Labels: cdc

#2393 Simplify PartitionArrangement
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/PartitionArrangement.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/PartitionAlignmentTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/execution/init/PartitionArrangementTest.java
Labels: enhancement

#2416 Fix serial tests in profile all
  pom.xml
Labels: build

#2383 Fix error handling in tryStartJob()
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/JobRepositoryTest.java
Labels: core, defect

#2413 Add windows-jenkins profile
  extensions/cdc-debezium/src/test/java/com/hazelcast/jet/cdc/AbstractCdcIntegrationTest.java
  extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/AbstractMySqlCdcIntegrationTest.java
  extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/AbstractPostgresCdcIntegrationTest.java
  extensions/elasticsearch/elasticsearch-5/src/test/java/com/hazelcast/jet/elastic/BaseElasticTest.java
  extensions/elasticsearch/elasticsearch-6/src/test/java/com/hazelcast/jet/elastic/BaseElasticTest.java
  extensions/elasticsearch/elasticsearch-7/src/test/java/com/hazelcast/jet/elastic/BaseElasticTest.java
  extensions/hadoop/src/test/java/com/hazelcast/jet/hadoop/impl/HadoopTestSupport.java
  extensions/s3/src/test/java/com/hazelcast/jet/s3/S3MockTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/JmsSourceIntegrationTest_RabbitMQ.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/connector/WriteJdbcPTest.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/test/IgnoreInJenkinsOnWindows.java
  pom.xml
Labels: build

#2418 Skip processing in-flight observable results when observer is cancelled
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/observer/ObservableImpl.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ObservableResultsTest.java
Labels: core, defect

#2390 [005] Make Debezium sequences public
  extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/ChangeRecord.java
  extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSerializerHooks.java
  extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/ChangeRecordImpl.java
  extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/WriteCdcP.java
  extensions/cdc-postgres/src/test/java/com/hazelcast/jet/cdc/postgres/MultiTableCacheIntegrationTest.java
  site/docs/tutorials/cdc-join.md
Labels: cdc
