Repository hazelcast/hazelcast-jet, pull requests merged in 2021-04, with the labels that each got.

#2887 Fix queue size display in Dot representation when default is changed
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/DAG.java
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java
  hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/DotTest.java
  hazelcast-jet-distribution/src/root/release_notes.txt
Labels: breaking-change-core, core, defect

#3012 Upgrade parquet to 1.12.0
  extensions/hadoop-dist/files-azure/src/root/NOTICE
  extensions/hadoop-dist/files-gcs/src/root/NOTICE
  extensions/hadoop-dist/files-s3/src/root/NOTICE
  extensions/hadoop-dist/hadoop-all/src/root/NOTICE
  hazelcast-jet-distribution/src/root/NOTICE
  pom.xml
Labels: dependencies

#3009 Limit the number of parallel partition reads for map/cache.
  hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/ReadMapOrCacheP.java
Labels: core, defect

#3014 Exclude log4j (1.2.x) from hadoop module dependencies
  extensions/hadoop-dist/files-azure/src/root/NOTICE
  extensions/hadoop-dist/files-gcs/src/root/NOTICE
  extensions/hadoop-dist/files-s3/src/root/NOTICE
  extensions/hadoop-dist/hadoop-all/src/root/NOTICE
  extensions/hadoop-dist/pom.xml
  extensions/hadoop/pom.xml
  hazelcast-jet-distribution/src/root/NOTICE
Labels: security

#3013 Update IMDG to 4.2 and kubernetes plugin to 2.2.2
  pom.xml
Labels: dependencies, enhancement

#3015 Fix httpcore-nio dependency to 4.4.13
  extensions/elasticsearch/elasticsearch-6/src/root/NOTICE
  hazelcast-jet-distribution/src/root/NOTICE
  pom.xml
Labels: dependencies, enhancement

#3023 More security
  extensions/elasticsearch/elasticsearch-5/pom.xml
  extensions/elasticsearch/elasticsearch-6/pom.xml
  extensions/elasticsearch/elasticsearch-7/pom.xml
  extensions/grpc/pom.xml
  extensions/hadoop-dist/files-azure/src/root/NOTICE
  extensions/hadoop-dist/files-gcs/src/root/NOTICE
  extensions/hadoop-dist/files-s3/src/root/NOTICE
  extensions/hadoop-dist/hadoop-all/src/root/NOTICE
  hazelcast-jet-distribution/src/root/NOTICE
  pom.xml
Labels: dependencies, security

#3024 Update Snakeyaml version to 1.26
  extensions/elasticsearch/elasticsearch-6/src/root/NOTICE
  pom.xml
Labels: security

#3028 Fix NOTICE file generation for extensions
  extensions/NOTICE-extensions.ftl
  extensions/avro/src/main/resources/NOTICE
  extensions/cdc-debezium/src/main/resources/NOTICE
  extensions/cdc-mysql/src/main/resources/NOTICE
  extensions/cdc-postgres/src/main/resources/NOTICE
  extensions/csv/src/main/resources/NOTICE
  extensions/elasticsearch/elasticsearch-5/pom.xml
  extensions/elasticsearch/elasticsearch-6/pom.xml
  extensions/elasticsearch/elasticsearch-6/src/main/resources/NOTICE
  extensions/elasticsearch/elasticsearch-7/src/main/resources/NOTICE
  extensions/grpc/src/main/resources/NOTICE
  extensions/hadoop-dist/files-azure/src/main/resources/NOTICE
  extensions/hadoop-dist/files-gcs/src/main/resources/NOTICE
  extensions/hadoop-dist/files-s3/src/main/resources/NOTICE
  extensions/hadoop-dist/hadoop-all/src/main/resources/NOTICE
  extensions/hadoop-dist/hadoop/src/main/resources/NOTICE
  extensions/hadoop-dist/src/main/resources/NOTICE
  extensions/hadoop/src/main/resources/NOTICE
  extensions/kafka/src/main/resources/NOTICE
  extensions/kinesis/src/main/resources/NOTICE
  extensions/pom.xml
  extensions/protobuf/src/main/resources/NOTICE
  extensions/python/src/main/resources/NOTICE
  extensions/s3/src/main/resources/NOTICE
  extensions/src/main/resources/NOTICE
  pom.xml
Labels: build

#3030 Merge content of NOTICE files
  NOTICE
  hazelcast-jet-distribution/src/NOTICE.ftl
  hazelcast-jet-distribution/src/root/NOTICE
Labels: build

#3025 Update Snakeyaml version to 1.26
  extensions/elasticsearch/elasticsearch-6/src/main/resources/NOTICE
  pom.xml
Labels: security

#3032 Release blog post for Jet 4.5
  hazelcast-jet-distribution/src/root/release_notes.txt
  site/website/blog/2021-04-23-jet-45-is-released.md
Labels: docs, docs-no-build, enhancement

#3034 Fixes to javadoc generation for Jet 4.5
  hazelcast-jet-distribution/pom.xml
Labels: build, javadoc

#3035 Fixes to javadoc generation for Jet 4.5
  hazelcast-jet-distribution/pom.xml
Labels: build, javadoc

#3036 Docs for 4.5
  site/javadoc/4.5.tar.gz
  site/website/all-versions.json
  site/website/attributes.json
  site/website/versioned_docs/version-4.5/api/data-structures.md
  site/website/versioned_docs/version-4.5/api/error-handling.md
  site/website/versioned_docs/version-4.5/api/pipeline.md
  site/website/versioned_docs/version-4.5/api/serialization.md
  site/website/versioned_docs/version-4.5/api/sources-sinks.md
  site/website/versioned_docs/version-4.5/api/spring.md
  site/website/versioned_docs/version-4.5/api/stateful-transforms.md
  site/website/versioned_docs/version-4.5/api/testing.md
  site/website/versioned_docs/version-4.5/architecture/execution-engine.md
  site/website/versioned_docs/version-4.5/concepts/processing-guarantees.md
  site/website/versioned_docs/version-4.5/design-docs/005-cdc-sources.md
  site/website/versioned_docs/version-4.5/enterprise/blue-green.md
  site/website/versioned_docs/version-4.5/enterprise/installation.md
  site/website/versioned_docs/version-4.5/enterprise/lossless-restart.md
  site/website/versioned_docs/version-4.5/enterprise/management-center.md
  site/website/versioned_docs/version-4.5/enterprise/off-heap.md
  site/website/versioned_docs/version-4.5/enterprise/operator-openshift.md
  site/website/versioned_docs/version-4.5/enterprise/security.md
  site/website/versioned_docs/version-4.5/get-started/first-job.md
  site/website/versioned_docs/version-4.5/get-started/installation.md
  site/website/versioned_docs/version-4.5/how-tos/custom-aggregate-operation.md
  site/website/versioned_docs/version-4.5/how-tos/custom-stream-source.md
  site/website/versioned_docs/version-4.5/how-tos/grpc.md
  site/website/versioned_docs/version-4.5/how-tos/observables.md
  site/website/versioned_docs/version-4.5/how-tos/operator.md
  site/website/versioned_docs/version-4.5/how-tos/stream-imap.md
  site/website/versioned_docs/version-4.5/operations/cdc.md
  site/website/versioned_docs/version-4.5/operations/cluster-sizing.md
  site/website/versioned_docs/version-4.5/operations/installation.md
  site/website/versioned_docs/version-4.5/operations/job-management.md
  site/website/versioned_docs/version-4.5/operations/kubernetes.md
  site/website/versioned_docs/version-4.5/operations/monitoring.md
  site/website/versioned_docs/version-4.5/sql/basic-commands.md
  site/website/versioned_docs/version-4.5/sql/ddl.md
  site/website/versioned_docs/version-4.5/sql/file-connector.md
  site/website/versioned_docs/version-4.5/sql/imap-connector.md
  site/website/versioned_docs/version-4.5/sql/intro.md
  site/website/versioned_docs/version-4.5/sql/kafka-connector.md
  site/website/versioned_docs/version-4.5/tutorials/cdc-join.md
  site/website/versioned_docs/version-4.5/tutorials/cdc-postgres.md
  site/website/versioned_docs/version-4.5/tutorials/cdc.md
  site/website/versioned_docs/version-4.5/tutorials/kafka.md
  site/website/versioned_docs/version-4.5/tutorials/kinesis.md
  site/website/versioned_docs/version-4.5/tutorials/map-join.md
  site/website/versioned_docs/version-4.5/tutorials/pulsar.md
  site/website/versioned_docs/version-4.5/tutorials/python.md
  site/website/versioned_docs/version-4.5/tutorials/windowing.md
  site/website/versions.json
Labels: docs, docs-no-build

#3037 Fix 4.5 download page
  site/website/modules.json
  site/website/pages/en/download.js
Labels: docs, docs-no-build
