Repository hazelcast/hazelcast-jet, pull requests merged in 2021-12, with the labels that each got.

#3074 Decommission download machine - update links
  site/docs/enterprise/management-center.md
  site/website/pages/en/download.js
  site/website/versioned_docs/version-4.0/enterprise/installation.md
  site/website/versioned_docs/version-4.0/enterprise/management-center.md
  site/website/versioned_docs/version-4.1.1/enterprise/installation.md
  site/website/versioned_docs/version-4.1.1/enterprise/management-center.md
  site/website/versioned_docs/version-4.2/enterprise/installation.md
  site/website/versioned_docs/version-4.2/enterprise/management-center.md
  site/website/versioned_docs/version-4.3.1/enterprise/installation.md
  site/website/versioned_docs/version-4.3.1/enterprise/management-center.md
  site/website/versioned_docs/version-4.4/enterprise/installation.md
  site/website/versioned_docs/version-4.4/enterprise/management-center.md
  site/website/versioned_docs/version-4.5.1/enterprise/installation.md
  site/website/versioned_docs/version-4.5.1/enterprise/management-center.md
  site/website/versioned_docs/version-4.5/enterprise/installation.md
  site/website/versioned_docs/version-4.5/enterprise/management-center.md
Labels: docs-no-build

#3079 Update avro to 1.11.0
  extensions/avro/src/main/resources/NOTICE
  extensions/hadoop-dist/files-azure/src/main/resources/NOTICE
  extensions/hadoop-dist/files-gcs/src/main/resources/NOTICE
  extensions/hadoop-dist/files-s3/src/main/resources/NOTICE
  extensions/hadoop-dist/hadoop-all/src/main/resources/NOTICE
  extensions/hadoop-dist/src/main/resources/NOTICE
  hazelcast-jet-distribution/src/root/NOTICE
  pom.xml
Labels: dependencies

#3078 Update log4j to 2.15.0
  extensions/cdc-debezium/pom.xml
  extensions/cdc-mysql/pom.xml
  extensions/cdc-postgres/pom.xml
  extensions/elasticsearch/elasticsearch-6/src/main/resources/NOTICE
  extensions/elasticsearch/elasticsearch-7/src/main/resources/NOTICE
  extensions/kinesis/pom.xml
  hazelcast-jet-distribution/src/root/NOTICE
  pom.xml
Labels: dependencies, security, severity:critical

#3080 Update aws sdk to 1.12.128
  extensions/hadoop-dist/files-s3/src/main/resources/NOTICE
  extensions/kinesis/src/main/resources/NOTICE
  hazelcast-jet-distribution/src/root/NOTICE
  pom.xml
Labels: dependencies

#3081 Update dependencies
  extensions/avro/src/main/resources/NOTICE
  extensions/cdc-debezium/src/main/resources/NOTICE
  extensions/cdc-mysql/src/main/resources/NOTICE
  extensions/cdc-postgres/src/main/resources/NOTICE
  extensions/csv/src/main/resources/NOTICE
  extensions/elasticsearch/elasticsearch-6/src/main/resources/NOTICE
  extensions/elasticsearch/elasticsearch-7/src/main/resources/NOTICE
  extensions/hadoop-dist/files-azure/src/main/resources/NOTICE
  extensions/hadoop-dist/files-gcs/src/main/resources/NOTICE
  extensions/hadoop-dist/files-s3/src/main/resources/NOTICE
  extensions/hadoop-dist/hadoop-all/src/main/resources/NOTICE
  extensions/hadoop-dist/src/main/resources/NOTICE
  extensions/kafka/src/main/resources/NOTICE
  extensions/kinesis/src/main/resources/NOTICE
  extensions/s3/src/main/resources/NOTICE
  hazelcast-jet-core/pom.xml
  hazelcast-jet-distribution/src/root/NOTICE
  licenses/override-THIRD-PARTY.properties
  pom.xml
Labels: dependencies

#3084 Update IMDG to 4.2.3
  pom.xml
Labels: dependencies

#3088 Docs for 4.5.2
  site/javadoc/4.5.2.tar.gz
  site/website/all-versions.json
  site/website/modules.json
  site/website/versioned_docs/version-4.5.2/api/data-structures.md
  site/website/versioned_docs/version-4.5.2/api/error-handling.md
  site/website/versioned_docs/version-4.5.2/api/pipeline.md
  site/website/versioned_docs/version-4.5.2/api/serialization.md
  site/website/versioned_docs/version-4.5.2/api/sources-sinks.md
  site/website/versioned_docs/version-4.5.2/api/spring.md
  site/website/versioned_docs/version-4.5.2/api/stateful-transforms.md
  site/website/versioned_docs/version-4.5.2/api/testing.md
  site/website/versioned_docs/version-4.5.2/architecture/execution-engine.md
  site/website/versioned_docs/version-4.5.2/concepts/processing-guarantees.md
  site/website/versioned_docs/version-4.5.2/design-docs/005-cdc-sources.md
  site/website/versioned_docs/version-4.5.2/enterprise/blue-green.md
  site/website/versioned_docs/version-4.5.2/enterprise/installation.md
  site/website/versioned_docs/version-4.5.2/enterprise/lossless-restart.md
  site/website/versioned_docs/version-4.5.2/enterprise/management-center.md
  site/website/versioned_docs/version-4.5.2/enterprise/off-heap.md
  site/website/versioned_docs/version-4.5.2/enterprise/operator-openshift.md
  site/website/versioned_docs/version-4.5.2/enterprise/security.md
  site/website/versioned_docs/version-4.5.2/get-started/first-job.md
  site/website/versioned_docs/version-4.5.2/get-started/installation.md
  site/website/versioned_docs/version-4.5.2/how-tos/custom-aggregate-operation.md
  site/website/versioned_docs/version-4.5.2/how-tos/custom-stream-source.md
  site/website/versioned_docs/version-4.5.2/how-tos/grpc.md
  site/website/versioned_docs/version-4.5.2/how-tos/observables.md
  site/website/versioned_docs/version-4.5.2/how-tos/operator.md
  site/website/versioned_docs/version-4.5.2/how-tos/stream-imap.md
  site/website/versioned_docs/version-4.5.2/operations/cdc.md
  site/website/versioned_docs/version-4.5.2/operations/cluster-sizing.md
  site/website/versioned_docs/version-4.5.2/operations/installation.md
  site/website/versioned_docs/version-4.5.2/operations/job-management.md
  site/website/versioned_docs/version-4.5.2/operations/kubernetes.md
  site/website/versioned_docs/version-4.5.2/operations/monitoring.md
  site/website/versioned_docs/version-4.5.2/sql/basic-commands.md
  site/website/versioned_docs/version-4.5.2/sql/imap-connector.md
  site/website/versioned_docs/version-4.5.2/sql/intro.md
  site/website/versioned_docs/version-4.5.2/sql/kafka-connector.md
  site/website/versioned_docs/version-4.5.2/tutorials/cdc-join.md
  site/website/versioned_docs/version-4.5.2/tutorials/cdc-postgres.md
  site/website/versioned_docs/version-4.5.2/tutorials/cdc.md
  site/website/versioned_docs/version-4.5.2/tutorials/kafka.md
  site/website/versioned_docs/version-4.5.2/tutorials/kinesis.md
  site/website/versioned_docs/version-4.5.2/tutorials/map-join.md
  site/website/versioned_docs/version-4.5.2/tutorials/pulsar.md
  site/website/versioned_docs/version-4.5.2/tutorials/python.md
  site/website/versioned_docs/version-4.5.2/tutorials/windowing.md
  site/website/versions.json
Labels: docs, docs-no-build

#3092 Update log4j to 2.17.0
  extensions/elasticsearch/elasticsearch-6/src/main/resources/NOTICE
  extensions/elasticsearch/elasticsearch-7/src/main/resources/NOTICE
  hazelcast-jet-distribution/src/root/NOTICE
  pom.xml
Labels: dependencies

#3093 Add release notes for 4.5.3
  hazelcast-jet-distribution/src/root/release_notes.txt
Labels: dependencies, docs-no-build

#3095 Docs for 4.5.3
  site/javadoc/4.5.3.tar.gz
  site/website/all-versions.json
  site/website/modules.json
  site/website/versioned_docs/version-4.5.3/api/data-structures.md
  site/website/versioned_docs/version-4.5.3/api/error-handling.md
  site/website/versioned_docs/version-4.5.3/api/pipeline.md
  site/website/versioned_docs/version-4.5.3/api/serialization.md
  site/website/versioned_docs/version-4.5.3/api/sources-sinks.md
  site/website/versioned_docs/version-4.5.3/api/spring.md
  site/website/versioned_docs/version-4.5.3/api/stateful-transforms.md
  site/website/versioned_docs/version-4.5.3/api/testing.md
  site/website/versioned_docs/version-4.5.3/architecture/execution-engine.md
  site/website/versioned_docs/version-4.5.3/concepts/processing-guarantees.md
  site/website/versioned_docs/version-4.5.3/design-docs/005-cdc-sources.md
  site/website/versioned_docs/version-4.5.3/enterprise/blue-green.md
  site/website/versioned_docs/version-4.5.3/enterprise/installation.md
  site/website/versioned_docs/version-4.5.3/enterprise/lossless-restart.md
  site/website/versioned_docs/version-4.5.3/enterprise/management-center.md
  site/website/versioned_docs/version-4.5.3/enterprise/off-heap.md
  site/website/versioned_docs/version-4.5.3/enterprise/operator-openshift.md
  site/website/versioned_docs/version-4.5.3/enterprise/security.md
  site/website/versioned_docs/version-4.5.3/get-started/first-job.md
  site/website/versioned_docs/version-4.5.3/get-started/installation.md
  site/website/versioned_docs/version-4.5.3/how-tos/custom-aggregate-operation.md
  site/website/versioned_docs/version-4.5.3/how-tos/custom-stream-source.md
  site/website/versioned_docs/version-4.5.3/how-tos/grpc.md
  site/website/versioned_docs/version-4.5.3/how-tos/observables.md
  site/website/versioned_docs/version-4.5.3/how-tos/operator.md
  site/website/versioned_docs/version-4.5.3/how-tos/stream-imap.md
  site/website/versioned_docs/version-4.5.3/operations/cdc.md
  site/website/versioned_docs/version-4.5.3/operations/cluster-sizing.md
  site/website/versioned_docs/version-4.5.3/operations/installation.md
  site/website/versioned_docs/version-4.5.3/operations/job-management.md
  site/website/versioned_docs/version-4.5.3/operations/kubernetes.md
  site/website/versioned_docs/version-4.5.3/operations/monitoring.md
  site/website/versioned_docs/version-4.5.3/sql/basic-commands.md
  site/website/versioned_docs/version-4.5.3/sql/imap-connector.md
  site/website/versioned_docs/version-4.5.3/sql/intro.md
  site/website/versioned_docs/version-4.5.3/sql/kafka-connector.md
  site/website/versioned_docs/version-4.5.3/tutorials/cdc-join.md
  site/website/versioned_docs/version-4.5.3/tutorials/cdc-postgres.md
  site/website/versioned_docs/version-4.5.3/tutorials/cdc.md
  site/website/versioned_docs/version-4.5.3/tutorials/kafka.md
  site/website/versioned_docs/version-4.5.3/tutorials/kinesis.md
  site/website/versioned_docs/version-4.5.3/tutorials/map-join.md
  site/website/versioned_docs/version-4.5.3/tutorials/pulsar.md
  site/website/versioned_docs/version-4.5.3/tutorials/python.md
  site/website/versioned_docs/version-4.5.3/tutorials/windowing.md
  site/website/versions.json
Labels: docs, docs-no-build
